### ISSUE TITLE
Future directions

### ISSUE THREAD

**Issue by Evizero** [lindahua/EmpiricalRisks.jl#4]
Hi! Thanks for all your amazing efforts.

Is this package still of interest to you? Since I am switching over my work and Machine Learning research to Julia I am in the process of writing a few libraries that I need. There are many cool things already established, but only "kinda", if you know what I mean.

Long story short, if you are still interested in maintaining this package (and the two sub-packages), I want to contribute the necessary things for getting them up to speed (or my biased interpretation of it; egoistically motivated). 

here's what I want to work on:
- **EmpiricalRisks.jl** currently collides with StatsBase in respect to `predict`. I would need them to play nice. 
- **Regression.jl**: since it's deterministic optimization, it would probably be better off making use of [Optim.jl](https://github.com/JuliaOpt/Optim.jl) where the optimization community is spending it's focus on. I think the two would be a great fit and it would reduce redundancy. Though, this point kinda depends on if my pull-request there (that introduces callback functions) gets through, because I need those.
- **SGDOptim.jl**: The mini-batch stream is very verbose to deal with because it is only iterated over once instead of multiple times... I wonder anyhow if it wouldn't be better to structure the package similar to Optim.jl in the sense that it is agnostic to where the function and gradient comes from and thus need not depend on EmpiricalRisks.jl

I'm asking because other packages, where I made pull requests, have slow to no response (not even negative) which slows me down enough to make it worth my while to do things from scratch. (I do have deadlines). I'd rather contribute to your great efforts though than doing a reboot, provided you are interested and agree with what I want to change.

What are your thoughts on this? Am I coming off as a crazy person?

**Comment by lindahua** [comment]
I am still maintaining the package. I have some students working on distributed optimization, and they rely on these packages to work. There will be a lot more algorithms added to these repos after they achieve something in research. In the mean time, PRs are definitely welcomed.

**Comment by Evizero** [comment]
That is great to hear! I am looking forward to this

**Comment by Evizero** [comment]
I have been thinking about how to resolve the `predict` collision with StatsBase. I can think of several ways to resolve this, none of which is ideal. I'm interested in your position on this
1. include StatsBase as dependency so that `predict` becomes a function of the StatsBase `predict` method. 
   
   Although this is the cleanest solution from the end-user perspective, I think this would really be an overkill because there is no real need for the dependency.
2. Rename the `predict` method to something like `pred` to avoid collision
   
   Not the prettiest solution but would do the job. It might not be that bad since this library is more of a backbone anyways. A front-end machine learning library would probably have to have some problem abstraction anyways 
3. Only cherry-pick the things one needs when importing your package, or use the explicit namespace to avoid ambiguity (like `EmpiricalRisks.predict()`).
   
   This would leave the package as it is. However, this puts the inconvenience on the user which isn't ideal. But maybe I am blowing this problem out of proportions

What are your thoughts on this?
