### ISSUE TITLE
Memory footprint

### ISSUE THREAD

**Issue by Evizero** [lindahua/EmpiricalRisks.jl#6]
Hi! While playing around with Regression.jl, I noticed that the memory allocations for `GD()` scale with the number of iterations as well as observations in the dataset. After some digging, I discovered that the source of this is the `predict` method of EmpiricalRisks.jl which allocates the predicted vector within the method. 

Since `Regression.solve!` calls `Regression.backtrack!` multiple times, which in turn calls `EmpiricalRisks.predict` multiple times, the memory footprint accumulates. So the issue is that the prediction vector gets allocated multiple times each iteration when using `Regression.solve!`

I have come up with a potential solution by implementing a `predict!` method that fills a preallocated prediction vector. Using this method I could rewrite `solve!` to preallocate the prediction vector only once

``` Julia
function predict!{T<:BlasReal}(pm::AffinePred, θ::StridedVector{T}, X::StridedMatrix{T}, r::StridedVector{T})
    d = pm.dim
    n = size(X,2)
    @_checkdims length(θ) == d + 1 && size(X,1) == d && n == length(r)
    b = convert(T, pm.bias) * θ[d+1]
    for col = 1:n
        @inbounds r[col] = b
        for row = 1:d
            @inbounds r[col] += X[row, col] * θ[row]
        end
    end
    r
end
```

Here is a benchmark:

``` Julia
d = 3
n = 1000000
w = randn(d+1)
X = randn(d, n)
t = sign(X'w[1:d] + w[d+1] + 0.01 * randn(n))

using EmpiricalRisks
pm = AffinePred(d, 1.)

@time predict(pm, w, X)
@time predict(pm, w, X)

r = zeros(n)
@time predict!(pm, w, X, r)
@time predict!(pm, w, X, r)

println("Loop with predict")
@time for i = 1:1000
  s = predict(pm, w, X)
end

println("Loop with predict!")
@time for i = 1:1000
  s = predict!(pm, w, X, r)
end
```

```
elapsed time: 0.356688159 seconds (21377200 bytes allocated)
elapsed time: 0.005305386 seconds (8000456 bytes allocated) <-- predict
elapsed time: 0.021158343 seconds (409856 bytes allocated)
elapsed time: 0.006868238 seconds (80 bytes allocated) <-- predict!
Loop with predict
elapsed time: 16.95238578 seconds (8000377088 bytes allocated, 43.88% gc time)
Loop with predict!
elapsed time: 4.788862339 seconds (0 bytes allocated)
```

What do you think? would you be interested in merging these changes if I create the PRs?

**Comment by lindahua** [comment]
This is very nice!

A PR is welcomed, and would make this happen sooner. Following the Julia convention, I would place the output array `r` as the first argument, preceding `pm` in `predict!`.

**Comment by Evizero** [comment]
Great! Ok, good to know. I will follow that convention. 

No worries, I will implement it. And with "it" I mean the necessary functions and tests for `value!`, `predict!`, and `value_and_addgrad!`, so that I can adapt Regression.jl accordingly after that PR is merged.

I am about half way done

**Comment by Evizero** [comment]
Could you consider tagging a new version? I could then change the require for [PR 10 of Regression](https://github.com/lindahua/Regression.jl/pull/10) and we could proceed there

**Comment by lindahua** [comment]
already tagged just now.
